SELECT* FROM BRIGHT_COFFEE_DATASET

---EXPLORATORY DATA ANALYSIS---

--- CHECKING NUMBER OF CATEGORIES.
SELECT DISTINCT PRODUCT_CATEGORY
FROM BRIGHT_COFFEE_DATASET
\
--- CHECKING THE NUMBER OF STORES.
SELECT DISTINCT STORE_LOCATION
FROM BRIGHT_COFFEE_DATASET;

--- CHECKING NUMBER OF PRODUCT TYPE
SELECT DISTINCT PRODUCT_TYPE
FROM BRIGHT_COFFEE_DATASET

----DATE AND TIME FUNCTIONS----
SELECT MIN (TRANSACTION_DATE)AS FIRST_OPERATING_DATE
FROM BRIGHT_COFFEE_DATASET

SELECT MAX (TRANSACTION_DATE)AS LAST_OPERATING_DATE
FROM BRIGHT_COFFEE_DATASET;

SELECT MIN(TRANSACTION_DATE)AS EARLIEST_TIME
FROM BRIGHT_COFFEE_DATASET;

SELECT MAX (TRANSACTION_DATE)AS LATEST_TIME
FROM BRIGHT_COFFEE_DATASET;

SELECT 
------------------------------------------------------------------------------------------------------------------

SELECT 
   TRANSACTION_DATE,
   DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
 CASE 
     WHEN DAYNAME(TRANSACTION_DATE)IN ('SAT','SUN') THEN 'WEEKEND'
     ELSE 'WEEKDAY'
     END AS DAY_CLASSIFICATION,
  MONTHNAME(TRANSACTION_DATE)AS MONTH_NAME,
      TRANSACTION_TIME,
 CASE 
     WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
     WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
     WHEN TRANSACTION_TIME >= '17:00:00' THEN 'EVENING'
     END AS TIME_BUCKET,
   HOUR(TRANSACTION_TIME) AS HOUR_OF_DAY,
     STORE_ID,
     STORE_LOCATION,
     PRODUCT_CATEGORY,
     PRODUCT_DETAIL,
     PRODUCT_TYPE,
  TRANSACTION_QTY*UNIT_PRICE AS REEVENUE,
COUNT(DISTINCT TRANSACTION_ID)AS NUMBER_OF_SALES 
FROM BRIGHT_COFFEE_DATASET
GROUP BY ALL;

